# Generated by Django 2.1.7 on 2019-05-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190527_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
