# Generated by Django 2.1.7 on 2019-05-24 21:49

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=9, verbose_name='Цена')),
                ('first_image', models.ImageField(null='media/no_image.png', upload_to=catalog.models.imagePath, verbose_name='Первое фото')),
                ('second_image', models.ImageField(null='media/no_image.png', upload_to=catalog.models.imagePath, verbose_name='Второе фото')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Заголовок')),
                ('manufacter', models.CharField(default='', max_length=50, verbose_name='Изготовитель')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Рейтинг')),
                ('category', models.CharField(editable=False, max_length=20)),
                ('clicks', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Accessorie',
            fields=[
                ('shopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.ShopItem')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
            ],
            bases=('catalog.shopitem',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('shopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.ShopItem')),
                ('os', models.CharField(default='Android', max_length=50, verbose_name='Система')),
                ('year', models.IntegerField(default=2010, verbose_name='Год')),
                ('camera', models.IntegerField(default=8, verbose_name='Камера')),
                ('display', models.CharField(default='1920x1080', max_length=50, verbose_name='Разрешение')),
                ('battery', models.IntegerField(default=1000, verbose_name='Батарея')),
                ('capacity', models.IntegerField(default=1800, verbose_name='Вместимость')),
                ('chip', models.CharField(default='MTK', max_length=50, verbose_name='Процессор')),
                ('color', models.CharField(default='черный', max_length=50, verbose_name='Цвет')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Есть Wi-fi?')),
                ('weight', models.IntegerField(default=400, verbose_name='Вес')),
            ],
            bases=('catalog.shopitem',),
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('accessorie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Accessorie')),
                ('features', models.CharField(max_length=50, verbose_name='Вход')),
                ('compatibility', models.CharField(max_length=50, verbose_name='Выход')),
            ],
            options={
                'verbose_name_plural': 'Кабеля',
            },
            bases=('catalog.accessorie',),
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('accessorie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Accessorie')),
                ('material', models.CharField(max_length=50, verbose_name='Материал')),
                ('design', models.CharField(max_length=50, verbose_name='Дизайн')),
            ],
            options={
                'verbose_name_plural': 'Чехлы',
            },
            bases=('catalog.accessorie',),
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('accessorie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Accessorie')),
                ('communication', models.CharField(max_length=50, verbose_name='Соединение')),
                ('frequency', models.CharField(max_length=50, verbose_name='Максимальная частота')),
                ('connectors', models.CharField(max_length=50, verbose_name='Разьем')),
            ],
            options={
                'verbose_name_plural': 'Наушники',
            },
            bases=('catalog.accessorie',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Device')),
                ('access', models.CharField(max_length=50, verbose_name='Доступ')),
                ('sim_format', models.CharField(max_length=50, verbose_name='Поддерживаемый формат SIM')),
            ],
            options={
                'verbose_name_plural': 'Телефоны',
            },
            bases=('catalog.device',),
        ),
        migrations.CreateModel(
            name='Sdcard',
            fields=[
                ('accessorie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Accessorie')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('speed', models.IntegerField(verbose_name='Скорость записи')),
            ],
            options={
                'verbose_name_plural': 'SD-карты',
            },
            bases=('catalog.accessorie',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Device')),
                ('has_pen', models.BooleanField(verbose_name='Есть стилус?')),
                ('has_keyboard', models.BooleanField(verbose_name='Есть клавиатура?')),
            ],
            options={
                'verbose_name_plural': 'Планшеты',
            },
            bases=('catalog.device',),
        ),
    ]
